CREATE TABLE test (id INT);

INSERT INTO test VALUES(0);
INSERT INTO test VALUES(1);
INSERT INTO test VALUES(2);
INSERT INTO test VALUES(3);
INSERT INTO test VALUES(4);
INSERT INTO test VALUES(5);
INSERT INTO test VALUES(6);
INSERT INTO test VALUES(7);
INSERT INTO test VALUES(8);
INSERT INTO test VALUES(9);

DELETE FROM test;

-- output:
-- Empty result set
SELECT * FROM test;
